<?php 

define("CONTROLLER", __DIR__.DIRECTORY_SEPARATOR.'controller'.DIRECTORY_SEPARATOR ) ;
define("VIEWS", __DIR__.DIRECTORY_SEPARATOR.'views'.DIRECTORY_SEPARATOR ) ;
define("MODEL", __DIR__.DIRECTORY_SEPARATOR.'model'.DIRECTORY_SEPARATOR ) ;
define("ASSETS", __DIR__.DIRECTORY_SEPARATOR.'assets'.DIRECTORY_SEPARATOR ) ;
define("RACINE", __DIR__.DIRECTORY_SEPARATOR ) ;

 ?>